In [52]:
%cd aws/pro601

[Errno 2] No such file or directory: 'aws/pro601'
/home/jovyan/work/aws/pro601

In [53]:
import boto3 
import pandas as pd
import requests
import time 
import json
from datetime import datetime 

try:
    s3 = boto3.client("s3")
    buckets = s3.list_buckets()
    print("Conexion exitosa")
    print(f"Tienes {len(buckets['Buckets'])} buckets en tu cuenta")
except Exception as e:
    print("Error")
    print(e)

Conexion exitosa
Tienes 2 buckets en tu cuenta

In [54]:
bucket_name = "pro601hugogarmon"

In [55]:
df_playas = pd.read_csv("Playas_España.csv")

df_playas = df_playas[["Nombre","Provincia","Término_M","Duchas","Aseos","Acceso_dis","Bandera_az","Longitud","X","Y","Grado_ocup","Grado_urba"]]

df_playas.head(5)

,Nombre,Provincia,Término_M,Duchas,Aseos,Acceso_dis,Bandera_az,Longitud,X,Y,Grado_ocup,Grado_urba
0,La Venus,Málaga,Marbella,Sí,Sí,Sí,No,650 metros,-543984.9557,4.370555e+06,Alto,Urbana
1,Las Cañas,Málaga,Marbella,Sí,Sí,No,No,1.100 metros,-529891.9081,4.367771e+06,Medio,Urbana
2,Calahonda,Málaga,Mijas,Sí,Sí,Sí,Sí,3.500 metros,-524448.3850,4.367937e+06,Medio / Alto,Urbana
3,El Charcón,Málaga,Mijas,Sí,No,No,No,800 metros,-517145.8264,4.370638e+06,Bajo,Semiurbana
4,L'Espigó,Alicante/Alacant,Altea,No,Sí,Sí,Sí,600 metros,-4975.9812,4.664878e+06,Alto,Urbana

In [56]:
codigos_playas = pd.read_csv(
    "Playas_codigos.csv",
    sep=";",
    encoding="Latin-1",
    dtype={'ID_PLAYA': str}
)
codigos_playas = codigos_playas.head(10)

display(codigos_playas)

api_key = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnYXJtb25yZXlodWdvQGdtYWlsLmNvbSIsImp0aSI6ImVjOTVmMDcyLWNmN2QtNDhjMi1iNmI2LTFhODI3MTg5YmM3ZSIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNzczOTE0NDU1LCJ1c2VySWQiOiJlYzk1ZjA3Mi1jZjdkLTQ4YzItYjZiNi0xYTgyNzE4OWJjN2UiLCJyb2xlIjoiIn0.cPT6_FLzgz6ikhSIjAvjPTdQ7D9Wof3Rkc8IJNxS_xI"
url_base = "https://opendata.aemet.es/opendata/api/prediccion/especifica/playa/0301101"
headers = {

    'accept': 'application/json',

    'api_key': api_key

}
hoy = datetime.now().strftime("year=%Y/month=%m/day=%d")

print("Conectando con AEMET")
res_inicial = requests.get(url_base, headers=headers)

info_acceso = res_inicial.json()
url_datos_reales = info_acceso['datos']
print(f"Obteniendo datos de: {url_datos_reales}")
res_final = requests.get(url_datos_reales)
datos = res_final.json()

print(datos)

for codigo in codigos_playas['ID_PLAYA']:
    url_base = f"https://opendata.aemet.es/opendata/api/prediccion/especifica/playa/{codigo}"

    res_inicial = requests.get(url_base, headers=headers)
    info_acceso = res_inicial.json()
    
    url_datos_reales = info_acceso['datos']
    res_final = requests.get(url_datos_reales)
    datos = res_final.json()


    s3.put_object(
        Bucket=bucket_name,
        Key=f"bronce/meteorologia/prediccion_playas/{hoy}/playa_{codigo}.json",
        Body=json.dumps(datos)
    )

    print(f"Ingestada: {codigo}")

,ID_PLAYA,NOMBRE_PLAYA,ID_PROVINCIA,NOMBRE_PROVINCIA,ID_MUNICIPIO,NOMBRE_MUNICIPIO,LATITUD,LONGITUD
0,0301101,Raco de l'Albir,3,Alacant/Alicante,3011,l'Alfàs del Pi,"38º 34' 31""","-00º 03' 52"""
1,0301401,Sant Joan / San Juan,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 22' 48""","-00º 24' 32"""
2,0301408,El Postiguet,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 20' 46""","-00º 28' 38"""
3,0301410,Saladar,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 17' 02""","-00º 31' 08"""
4,0301808,La Roda,3,Alacant/Alicante,3018,Altea,"38º 36' 29""","-00º 02' 16"""
5,0301809,Cap Blanch,3,Alacant/Alicante,3018,Altea,"38º 35' 36""","-00º 03' 10"""
6,0303102,Llevant / Playa de Levante,3,Alacant/Alicante,3031,Benidorm,"38º 32' 12""","-00º 07' 05"""
7,0303104,Ponent / Playa de Poniente,3,Alacant/Alicante,3031,Benidorm,"38º 32' 14""","-00º 08' 55"""
8,0304105,Cala Fustera,3,Alacant/Alicante,3041,Benissa,"38º 39' 53""","0º 05' 16"""
9,0304704,La Fossa,3,Alacant/Alicante,3047,Calp,"38º 38' 46""","0º 04' 24"""

Conectando con AEMET
Obteniendo datos de: https://opendata.aemet.es/opendata/sh/88d5d1af
[{'origen': {'productor': 'Agencia Estatal de Meteorología - AEMET. Gobierno de España', 'web': 'http://www.aemet.es', 'language': 'es', 'copyright': '© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.', 'notaLegal': 'http://www.aemet.es/es/nota_legal'}, 'elaborado': '2026-04-15T08:50:18', 'nombre': "Raco de l'Albir", 'localidad': 3011, 'prediccion': {'dia': [{'estadoCielo': {'value': '', 'f1': 100, 'descripcion1': 'despejado', 'f2': 100, 'descripcion2': 'despejado'}, 'viento': {'value': '', 'f1': 210, 'descripcion1': 'flojo', 'f2': 210, 'descripcion2': 'flojo'}, 'oleaje': {'value': '', 'f1': 310, 'descripcion1': 'débil', 'f2': 310, 'descripcion2': 'débil'}, 'tMaxima': {'value': '', 'valor1': 20}, 'sTermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tAgua': {'value': '', 'valor1': 16}, 'uvMax': {'value': '', 'valor1': 7}, 'fecha': 20260415, 'tmaxima': {'value': '', 'valor1': 20}, 'stermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tagua': {'value': '', 'valor1': 16}}, {'estadoCielo': {'value': '', 'f1': 100, 'descripcion1': 'despejado', 'f2': 100, 'descripcion2': 'despejado'}, 'viento': {'value': '', 'f1': 210, 'descripcion1': 'flojo', 'f2': 210, 'descripcion2': 'flojo'}, 'oleaje': {'value': '', 'f1': 310, 'descripcion1': 'débil', 'f2': 310, 'descripcion2': 'débil'}, 'tMaxima': {'value': '', 'valor1': 20}, 'sTermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tAgua': {'value': '', 'valor1': 17}, 'uvMax': {'value': '', 'valor1': 7}, 'fecha': 20260416, 'tmaxima': {'value': '', 'valor1': 20}, 'stermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tagua': {'value': '', 'valor1': 17}}, {'estadoCielo': {'value': '', 'f1': 100, 'descripcion1': 'despejado', 'f2': 100, 'descripcion2': 'despejado'}, 'viento': {'value': '', 'f1': 210, 'descripcion1': 'flojo', 'f2': 210, 'descripcion2': 'flojo'}, 'oleaje': {'value': '', 'f1': 310, 'descripcion1': 'débil', 'f2': 310, 'descripcion2': 'débil'}, 'tMaxima': {'value': '', 'valor1': 21}, 'sTermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tAgua': {'value': '', 'valor1': 16}, 'uvMax': {'value': '', 'valor1': 7}, 'fecha': 20260417, 'tmaxima': {'value': '', 'valor1': 21}, 'stermica': {'value': '', 'valor1': 450, 'descripcion1': 'suave'}, 'tagua': {'value': '', 'valor1': 16}}]}, 'id': 301101}]
Ingestada: 0301101
Ingestada: 0301401
Ingestada: 0301408
Ingestada: 0301410
Ingestada: 0301808
Ingestada: 0301809
Ingestada: 0303102
Ingestada: 0303104
Ingestada: 0304105
Ingestada: 0304704

In [57]:
ruta_catalogo_s3 = "bronce/catalogos/guia_playas/v1/playas.csv"

with open("Playas_codigos.csv", "rb") as f:
    s3.put_object(
        Bucket=bucket_name,
        Key=ruta_catalogo_s3,
        Body=f,
        Metadata={'origen': 'Portal de Datos Abiertos de ESRI'} 
    )
print(f"Catálogo subido a: {ruta_catalogo_s3}")

Catálogo subido a: bronce/catalogos/guia_playas/v1/playas.csv